Add ordered_remove to remove target id that are not useful
only one ICE left without this patch:
523.xalancbmk_r.     lto1: error: reference to dead statement.
cgraph.c:3473 verify_cgraph_node->cgraph_node::verify_node.

if add this patch:
500.perfbench:
	error: in expand_call_inline, at tree-inline.c:4614.      gcc_checking_assert (cg_edge);
520.omnetpp_r:
	error: in speculative_call_info, at cgraph.c:1128.   gcc_assert (e->speculative && !e->indirect_unknown_callee);
523.xalancbmk_r:
	error: reference to dead statement.  cgraph.c:3473   verify_cgraph_node failed

maybe caused by incorrectly remove the target ids, which caused the
speculative_call_info fail to find the indirect edges or references.